config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :redirections, only: [:index, :edit, :update] do
      resources :blocks, only: [:create]
      resources :unlinks, only: [:create]
    end
    root "redirections#index"
  end

  namespace :api do
    # We use the *slug* as the redirection ID because the Slack bot (this
    # API's only user) can only get the slug right now.
    resources :redirections, only: [], param: :slug do
      resources :blocks, only: [:create]
      resources :unlinks, only: [:create]
    end
  end

  get "feed", to: "feeds#show", defaults: { format: :atom }
  get ":slug/next", to: "redirections#next"
  get ":slug/previous", to: "redirections#previous"
  resources :existing_slugs, only: :show

  root "homes#show"
end

app/models/redirection.rb
class Redirection < ActiveRecord::Base
  belongs_to :next, class_name: "Redirection", optional: true
  has_one :previous, class_name: "Redirection", foreign_key: "next_id"

  validates :next_id, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  validates :url, presence: true
  validate :unique_url_with_normalized_urls

  scope :in_ring_order, -> { order(next_id: :desc) }
  scope :latest_first, -> { order(created_at: :desc) }
  scope :order_nulls_last, ->(args) do
    sql = %[#{args["sort_key"]} #{args["sort_dir"]} NULLS LAST]
    order(sanitize_sql_for_order(Arel.sql(sql)))
  end

  def self.most_recent
    latest_first.first
  end

  def next_url
    self.next.url
  end

  def previous_url
    previous.url
  end

  def tag_uri
    date = created_at.iso8601

    "tag:#{UNCHANGING_HOSTNAME},#{date}:#{url}"
  end

  def unlink
    previous_redirection = previous
    next_redirection = self.next

    self.class.transaction do
      destroy!
      previous_redirection.update!(next: next_redirection)
    end
  end

  private

  def unique_url_with_normalized_urls
    if url.present?
      uri = URI.parse(url)
      matching_redirection = Redirection.where.not(slug: slug).all.detect do |redirection|
        UriComparison.same_normalized_uri?(uri, URI.parse(redirection.url))
      end
      if matching_redirection
        errors.add(:url, "is already taken by #{matching_redirection.slug}")
      end
    end
  end
end

app/controllers/admin/redirections_controller.rb
class Admin::RedirectionsController < AdminController
  DEFAULT_SORT_PARAMS = {"sort_key" => "next_id", "sort_dir" => "desc"}

  def index
    sort_by = DEFAULT_SORT_PARAMS.merge(sort_params)
    @redirections = Redirection.order_nulls_last(sort_by)
  end

  def edit
    @redirection = Redirection.find_by(id: params[:id])
  end

  def update
    @redirection = Redirection.find_by(id: params[:id])

    if @redirection.update(redirection_params)
      flash[:success] = "Updated #{@redirection.slug}"
      redirect_to admin_redirections_path
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  private

  def redirection_params
    params.require(:redirection).permit(:url)
  end

  def sort_params
    params.permit(:sort_key, :sort_dir)
  end
end

app/controllers/redirections_controller.rb
class RedirectionsController < ApplicationController
  before_action :ensure_referrer_is_not_localhost
  before_action :ensure_referrer_is_not_blocked
  before_action :ensure_request_is_not_from_a_bot
  before_action :ensure_request_is_not_a_subdomain_of_an_existing_site
  before_action :ensure_slug_matches_original_domain

  def next
    redirection = find_or_create_redirection

    redirect_to redirection.next_url, allow_other_host: true
  end

  def previous
    redirection = find_or_create_redirection

    redirect_to redirection.previous_url, allow_other_host: true
  end

  private

  def find_or_create_redirection
    if existing_redirection
      existing_redirection.tap do |redirection|
        redirection.touch(:last_seen_at)
      end
    else
      # Always log headers when possibly creating a new Redirection.
      # This ensures that if something goes wonky, we can look back through the
      # logs.
      log_headers
      create_redirection || use_fallback_redirection
    end
  end

  def create_redirection
    if Rails.configuration.disallow_creating_new_redirections
      false
    else
      RedirectionCreation.perform(
        referrer,
        params[:slug],
        open: !Rails.configuration.closed
      )
    end
  end

  def log_headers
    if referrer.blank?
      tagged_log "Referrer is BLANK! (Maybe they set `Referrer-Policy: no-referrer`?)"
    else
      tagged_log "Referrer: #{referrer}"
    end
    tagged_log "Here are all of the HTTP headers:"
    tagged_log http_headers
  end

  def use_fallback_redirection
    tagged_log "Redirection creation failed."
    if request.env["HTTP_UPGRADE_INSECURE_REQUESTS"].present?
      tagged_log "It likely failed because the links use HTTP instead of HTTPS"
    end
    Redirection.first
  end

  def referrer
    request.env["HTTP_REFERER"]
  end

  def http_headers
    http_only = ->(key, _) { key.start_with?("HTTP") }
    cookie_header = ->(key, _) { key == "HTTP_COOKIE" }
    request.env.select(&http_only).reject(&cookie_header)
  end

  def tagged_log(message)
    logger.info "[#{params[:slug]}] #{message}"
  end

  def ensure_referrer_is_not_localhost
    if creating_new_redirection?
      if HostValidator.new(referrer).invalid?
        redirect_to page_path("localhost")
      end
    end
  end

  def ensure_referrer_is_not_blocked
    if creating_new_redirection?
      if Block.new(referrer).blocked?
        redirect_to Redirection.first.url, allow_other_host: true
      end
    end
  end

  def ensure_request_is_not_from_a_bot
    if creating_new_redirection?
      user_agent = request.env["HTTP_USER_AGENT"]
      if DeviceDetector.new(user_agent).bot?
        log_with_headers "Detected a bot with user agent: #{user_agent}"
        redirect_to Redirection.first.url, allow_other_host: true
      end
    end
  end

  def ensure_request_is_not_a_subdomain_of_an_existing_site
    if creating_new_redirection?
      referrer_without_leading_subdomain = URI.parse(referrer).host.
        sub(/^[^.]+\./, "")
      match = Redirection.all.find { |r| URI.parse(r.url).host == referrer_without_leading_subdomain }
      if match
        log_with_headers "Trying to add a redirection for #{referrer_without_leading_subdomain} which conflicts with existing #{match.url}"
        redirect_to Redirection.first.url, allow_other_host: true
      end
    end
  end

  def ensure_slug_matches_original_domain
    if referrer && existing_redirection.present?
      referrer_host = normalized_host(referrer)
      if referrer_host != normalized_host(existing_redirection.url)
        log_with_headers "Slug's URL (#{existing_redirection.url}) does not match incoming referrer (normalized to #{referrer_host})"
        redirect_to existing_slug_path(params[:slug])
      end
    end
  end

  def log_with_headers(message)
    tagged_log message
    log_headers
  end

  def normalized_host(url)
    URI.parse(url).normalize.host.sub(/^www\./, "")
  end

  def creating_new_redirection?
    referrer && existing_redirection.nil?
  end

  def existing_redirection
    @_existing_redirection = params[:slug] &&
      Redirection.find_by(slug: params[:slug])
  end
end

app/views/admin/redirections/edit.html.erb
<h1>Editing <code><%= @redirection.slug %></code></h1>

<p>Original URL: <%= @redirection.original_url %></p>

<%= simple_form_for [:admin, @redirection] do |form| %>
  <%= form.input :url, label: "URL" %>
  <%= form.submit %>
<% end %>

app/views/admin/redirections/index.html.erb
<h2>Sort by</h2>
<section class="sort">
  <%= link_to(
    "Ring order",
    admin_redirections_path(sort_key: "next_id", sort_dir: "desc")
  ) %>
  <%= link_to(
    "Most recently seen",
    admin_redirections_path(sort_key: "last_seen_at", sort_dir: "desc")
  ) %>
  <%= link_to(
    "Least recently seen",
    admin_redirections_path(sort_key: "last_seen_at", sort_dir: "asc")
  ) %>
</section>

<h2>Redirections</h2>
<section class="redirections">
  <div class="header-row">
    <div class="redirection">
      <div>Slug</div>
      <div>URL</div>
      <div>Original URL</div>
      <div>Last seen</div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>

  <% @redirections.each do |redirection| %>
    <div class="redirection" data-id="<%= redirection.id %>">
      <div class="slug">
        <label>Slug</label>
        <span class="content"><%= redirection.slug %></span>
      </div>
      <div class="url">
        <label>URL</label>
        <span class="content"><%= link_to redirection.url, redirection.url %></span>
      </div>
      <div class="original-url">
        <label>Original URL</label>
        <%= link_to redirection.original_url, redirection.original_url %>
      </div>
      <div class="last-seen">
        <label>Last seen</label>
        <%= time_ago_in_words(
          redirection.last_seen_at || redirection.created_at
        ) %>
      </div>
      <div class="edit">
        <%= link_to "Edit", edit_admin_redirection_path(redirection) %>
      </div>
      <div class="block-button">
        <%= button_to "Block and unlink", admin_redirection_blocks_path(redirection) %>
      </div>
      <div class="unlink-button">
        <%= button_to "Unlink", admin_redirection_unlinks_path(redirection) %>
      </div>
    </div>
  <% end %>
</section>